language: node_js
node_js:
  - 13

services:
  - docker

install:
  - echo "Executing install section"

before_script:
  - echo "Executing before_scripts section"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-frontend .
  - docker tag udagram-frontend segunbabalola/udagram-frontend:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push segunbabalola/udagram-frontend:latest
